kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
        app: mongodb
        id: "0"
  template:
    metadata:
      labels:
        app: mongodb
        id: "0"
    spec:
      containers:
      - name: kafka
        image: mongo:4.2-bionic
        ports:
        - containerPort: 27017
        #env:
        #  - name: MONGO_INITDB_ROOT_USERNAME
        #    value: nexx
        #  - name: MONGO_INITDB_ROOT_PASSWORD
        #    value: "123456789"

