apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongodb
spec:
  ports:
  - port: 27017 
    name: mongo-port
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
    id: "0"
  type: NodePort
